// Notification event type constants used by triggerNotification() and NotificationsView checklist.

export const NOTIFICATION_EVENTS = {
  QUOTE_REQUEST_SENT: 'QUOTE_REQUEST_SENT',
  RECONCILIATION_SUBMITTED: 'RECONCILIATION_SUBMITTED',
  TRANSFER_SHIPPED: 'TRANSFER_SHIPPED',
  TRANSFER_RECEIVED: 'TRANSFER_RECEIVED',
  TRANSFER_DISCREPANCY: 'TRANSFER_DISCREPANCY',
  PRODUCT_COMPLETE: 'PRODUCT_COMPLETE',
  USER_ADDED: 'USER_ADDED',
  SKU_DELETED: 'SKU_DELETED',
  LARGE_INVENTORY_ADJUSTMENT: 'LARGE_INVENTORY_ADJUSTMENT',
  SKU_BELOW_PAR: 'SKU_BELOW_PAR',
  SKU_AUTO_DELETED: 'SKU_AUTO_DELETED',
  PHYSICAL_COUNT_OVERDUE: 'PHYSICAL_COUNT_OVERDUE',
};

export const EVENT_LABELS = {
  QUOTE_REQUEST_SENT: 'Quote Request Sent',
  RECONCILIATION_SUBMITTED: 'Reconciliation Submitted',
  TRANSFER_SHIPPED: 'Transfer Shipped',
  TRANSFER_RECEIVED: 'Transfer Received',
  TRANSFER_DISCREPANCY: 'Transfer Discrepancy',
  PRODUCT_COMPLETE: 'Product Complete',
  USER_ADDED: 'User Added',
  SKU_DELETED: 'SKU Deleted',
  LARGE_INVENTORY_ADJUSTMENT: 'Large Inventory Adjustment',
  SKU_BELOW_PAR: 'SKU Below Par',
  SKU_AUTO_DELETED: 'SKU Auto-Deleted',
  PHYSICAL_COUNT_OVERDUE: 'Physical Count Overdue',
};

// Display ordering for checklists
export const EVENT_ORDER = [
  'QUOTE_REQUEST_SENT',
  'RECONCILIATION_SUBMITTED',
  'TRANSFER_SHIPPED',
  'TRANSFER_RECEIVED',
  'TRANSFER_DISCREPANCY',
  'PRODUCT_COMPLETE',
  'USER_ADDED',
  'SKU_DELETED',
  'LARGE_INVENTORY_ADJUSTMENT',
  'SKU_BELOW_PAR',
  'SKU_AUTO_DELETED',
  'PHYSICAL_COUNT_OVERDUE',
];
